name: Deploy Eora

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enviar apenas alterações
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.nuvemshop.com.br
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps-legacy
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
